[package]
name = "presentation"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = { version="4", features=["rustls"] }
actix-files = "0.6.2"
actix-rt = "2.8.0"
tokio = { version = "1.20.0", features = ["full"]}
